# Generated by Django 4.2.16 on 2024-10-11 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinterface', '0045_remove_teammember_team_teammember_teams_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='public_overview_password',
            field=models.CharField(blank=True, help_text='Wenn kein Passwort gesetzt ist, ist die öffentliche Übersichtsseite nicht zugänglich', max_length=64, null=True),
        ),
        migrations.DeleteModel(
            name='UserProjectAssignment',
        ),
    ]
