# Generated by Django 4.2.16 on 2024-10-14 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinterface', '0046_alter_project_public_overview_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='code',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='teammember',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='mattermost_user',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='teammember',
            name='picture_string',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='teammember',
            name='short',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='teammember',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
