# Generated by Django 4.2.16 on 2024-10-14 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinterface', '0048_remove_teammember_picture_string_teammember_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='role',
            field=models.CharField(blank=True, choices=[('TL', 'Teamleitung'), ('DEV', 'Developer'), ('ORG', 'Organisation'), ('NA', 'Nicht zugewiesen')], max_length=3),
        ),
    ]
