# Generated by Django 4.2.16 on 2024-10-14 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinterface', '0049_alter_teammember_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='homepage',
            field=models.URLField(blank=True),
        ),
    ]
