# Generated by Django 4.2.16 on 2024-10-14 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinterface', '0050_teammember_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
